apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: searchs
  template:
    metadata:
      labels:
        app: searchs
    spec:
      containers:
        - name: searchs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
